version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install -r requirements.txt
      - python testperrikulos.py
      - COMMIT_HASH="$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7")"
      - IMAGE_TAG="latest"
      - printenv
  build:
    commands:
      - docker build -f Dockerfile -t perrikulos-ecr-private-repo-1 .
      - docker tag perrikulos-ecr-private-repo-1:$IMAGE_TAG 094887935327.dkr.ecr.us-west-2.amazonaws.com/perrikulos-ecr-private-repo-1:$IMAGE_TAG

    post_build:
      commands:
        - docker push docker push 094887935327.dkr.ecr.us-west-2.amazonaws.com/perrikulos-ecr-private-repo-1:$IMAGE_TAG
        - export IMAGE_NAME='ecs-devops-sandbox'
        - export IMAGE_URI=094887935327.dkr.ecr.us-west-2.amazonaws.com/perrikulos-ecr-private-repo-1:$IMAGE_TAG
