version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install -r requirements.txt
      - python testperrikulos.py
      - COMMIT_HASH="$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7")"
      - IMAGE_TAG="latest"
      - printenv
  build:
    commands:
      - docker build -f Dockerfile -t perrikulos-ecr-public-repo .
      - docker tag perrikulos-ecr-public-repo:$IMAGE_TAG public.ecr.aws/i3a0t0o0/perrikulos-ecr-public-repo:$IMAGE_TAG

    post_build:
      commands:
        - docker push public.ecr.aws/i3a0t0o0/perrikulos-ecr-public-repo:$IMAGE_TAG
        - export IMAGE_NAME='ecs-devops-sandbox'
        - export IMAGE_URI=public.ecr.aws/i3a0t0o0/perrikulos-ecr-public-repo:$IMAGE_TAG
